/* eslint-disable react/jsx-indent */
import React from 'react';
import Section from '../components/Code/Section';
import TextHeading from '../components/Code/TextHeading';
import TextSubHeading from '../components/Code/TextSubHeading';
import TextOnly from '../components/Code/TextOnly';
import TextAndCode from '../components/Code/TextAndCode';
import Text from '../components/Code/Text';
import Code from '../components/Code/Code';

export default function WritingSmartContracts() {
  return (
    <>
      <Section>
        <TextOnly>
          <TextHeading>
            Writing Smart Contracts for ParallelChain
          </TextHeading>
          <Text>
            By the end of this document, you should be able to:
          </Text>
          <ol>
            <li>
              <Text>
                Describe what a Smart Contract is.
              </Text>
            </li>
            <li>
              <Text>
                Describe how a smart contract relates with the key-value
                store and the blockchain log of a ParallelChain™ network.
              </Text>
            </li>
            <li>
              <Text>
                Write smart contracts for ParallelChain™ in the Go programming
                language using the ParallelChain™ Smart Contract API.
              </Text>
            </li>
            <li>
              <Text>
                Compile and package the smart contracts you have developed,
                and deploy them to a running ParallelChain™ network.
              </Text>
            </li>
            <li>
              <Text>
                Invoke deployed Smart Contracts through: 1. Applications written
                with the ParralelChain™ Client API, and 2. Using the ParallelChain™
                Admin CLI.
              </Text>
            </li>
          </ol>
        </TextOnly>
      </Section>
      <Section>
        <TextOnly>
          <TextSubHeading>
            What is a Smart Contract?
          </TextSubHeading>
          <Text>
            In the eyes of a developer or a system administrator, a ‘Smart Contract’
            is simply an executable file, generated by compiling programmer-written
            code into a portable format, and installed in the peer nodes of a
            blockchain network.
          </Text>
          <Text>
            In ParallelChain™ networks, these executable files (technically, a shared
            library, without a main method) contain business logic that interacts with
            a key-value database (PCoreDB) and a blockchained log to facilitate real-life
            activities, including important business practices. These activities can
            include everything from the more pedestrian uses of blockchain, e.g.
            creation and transfer of ownership of digital assets, to more creative
            applications involving emerging technologies, e.g. secure logging of
            events captured by always-on IoT devices.
          </Text>
        </TextOnly>
        <TextAndCode>
          <Text>
            This is weird code.
          </Text>
          <Code>
  {`import React from 'react';
  import { makeStyles } from '@material-ui/core/styles';

  const useStyles = makeStyles((t) => ({
    default: {
      color: t.palette.neutral.white,
    },
  }));

  export default function Code({ children }) {
    const classes = useStyles();

    return (
      <pre>
        <code className={classes.default}>
          { children }
        </code>
      </pre>
    );
  }`}
          </Code>
        </TextAndCode>
      </Section>
    </>
  );
}
